### ISSUE TITLE
please support alternative regex engines

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Regexp-Pattern#2]
For my uses of Regexp::Pattern::License, I want to explore use of alternative regex engines - in particular these seem interesting to me:

 * re::engine::RE2
 * re::engine::PCRE2
 * Regexp::Grammars

Seems sensible for Regexp::Pattern to support alternate regex engines generally.

**Comment by jonassmedegaard** [comment]
I will go ahead and implement option "engine" in Regexp::Pattern::License.  Maybe we need not align on option names generally - I understand now how Test::Regexp::Pattern simply needs local examples to take it into account. Clever open-ended design!

Please simply close this if you (understand my proposal but) disagree that this makes sense generally.

**Comment by perlancar** [comment]
I'm all for supporting alternate regex engines. PR welcome :) Or maybe tell me how you would like to use it in RP:License and we'll come up with an appropriate API for RP.

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-01-04 00:59:49)
> I'm all for supporting alternate regex engines. PR welcome :) Or maybe 
> tell me how you would like to use it in RP:License and we'll come with 
> an appropriate API for RP.

Here's my current draft: https://salsa.debian.org/build-common-team/regexp-pattern-license/commit/50f9877

Not sure if it makes sense to implement it in Regexp::Pattern -
when recommended to provide pre-generated regexes.

But might make sense to encourage using same name across pattern set.


But I am sure you got good ideas :-)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
I think code like this:

    if ( $args{engine} ) {
			if ( $args{engine} eq 'PCRE2' ) {
				use re::engine::PCRE2;
				return qr/$pat/;
			}
			elsif ( $args{engine} eq 'RE2' ) {
				use re::engine::RE2;
				return qr/$pat/;
			}
			else {
				die "Unsupported regexp engine \"$args{engine}\"";
			}
		}
		else {
			return qr/$pat/;
		}

will not do what you want, because the "use re::engine::Foo" statement will run in compile time, and thus the effect will be that the last "use re::engine::Foo" statement will take effect.

**Comment by perlancar** [comment]
In the add-engine-option branch, I've added an -engine option in the import interface and re() interface. The code now requires Require::Hook::More.

To test this out, try installing Regexp::Pattern::Test::re_engine and re::engine::PCRE2 also. Then:

    # ok
    %  perl -E'use Regexp::Pattern; re("Test::re_engine::contains_code_construct")'

    # dies because re::engine::PCRE2 does not support (?{ ... }) consruct
    %  perl -E'use Regexp::Pattern; re("Test::re_engine::contains_code_construct", {-engine=>"PCRE2"})'

Despite looking like a per-pattern option, this is a per-module option and once loaded you cannot request a different engine for patterns in the same Regexp::Pattern::* module (well technically you can by reloading the module.)

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-01-04 06:38:12)
> I think code like this:
> 
>     if ( $args{engine} ) {
>                         if ( $args{engine} eq 'PCRE2' ) {
>                                 use re::engine::PCRE2;
>                                 return qr/$pat/;
>                         }
>                         elsif ( $args{engine} eq 'RE2' ) {
>                                 use re::engine::RE2;
>                                 return qr/$pat/;
>                         }
>                         else {
>                                 die "Unsupported regexp engine \"$args{engine}\"";
>                         }
>                 }
>                 else {
>                         return qr/$pat/;
>                 }
> 
> will not do what you want, because the "use re::engine::Foo" statement 
> will run in compile time, and thus the effect will be that the last 
> "use re::engine::Foo" statement will take effect.

those re::engine::* (at least the ones above which I have looked at) 
apply to a lexical context.  They even (but not yet tested by me) stack, 
so you should be able to do this:

```perl
$foo_re = qr/^foo/;
{
	use re::engine::PCRE2;
	$bar_re = qr/^bar/;

	use re::engine::RE2;
	$baz_re = qr/^baz/;

	no use re::engine::RE2;
	$bof_re = qr/^bof/;
}

...where ($foo_re uses builtin regexes and) $bof_re uses PCRE2.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
% perl -E'if (0) { use re::engine::PCRE2; $re = qr/(?{1})/ } else { $re = qr/1/ }'
    Eval-group not allowed at runtime, use re 'eval' in regex m/(?{1})/ at -e line 1.

So in the above code, even though you think the if block is not being executed, it is compiled with PCRE2 and thus die with an error.

**Comment by perlancar** [comment]
> ```
> % perl -E'if (0) { use re::engine::PCRE2; $re = qr/(?{1})/ } else { $re = qr/1/ }'
> Eval-group not allowed at runtime, use re 'eval' in regex m/(?{1})/ at -e line 1.
> ```
> 
> So in the above code, even though you think the if block is not being executed, it is compiled with PCRE2 and thus die with an error.

Which, come to think of it again, is not a problem in your case. So never mind :)

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-01-04 08:40:50)
> I've added an -engine option in the import interface and re() 
> interface. The code now requires Require::Hook::More.

Oh.  I was really happy that Regexp::Pattern did _not_ require many 
non-core modules.  Please consider relaxing that new requirement to be 
optional - and do that without involving _other_ non-core modules like 
Module::Load::Conditional, e.g. by use of Module::Load::Conditional 
(which is in core).


Thanks for considering,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
Agreed. Ideally Regexp::Pattern should not depend on any non-core modules.

I've made Require::Hook::More an optional dependency. And remove requirement of perl 5.10.1 as well. I'd be open to replacing Require::Hook::More with some other core module too.

Do you think the picking the regexp engine option, as I implemented in the branch, is useful (to you, and in a more general sense)? I tend to think this is something that each Regexp::Pattern::* module should decide to use. Need to consider more real world cases.

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-01-05 05:55:31)
> Agreed. Ideally Regexp::Pattern should not depend on any non-core 
> modules.
> 
> I've made Require::Hook::More an optional dependency. And remove 
> requirement of perl 5.10.1 as well. I'd be open to replacing 
> Require::Hook::More with some other core module too.
> 
> Do you think the picking the regexp engine option, as I implemented in 
> the branch, is useful (to you, and in a more general sense)? I tend to 
> think this is something that each Regexp::Pattern::* module should 
> decide to use. Need to consider more real world cases.

Technically it might be most sensible that each module implements 
support - I am not sure about that, and guess you are more skilled and 
can better recognize what are the options.

Principally my thinking is that it would make best sense if each each 
RP::* module provides "source regexes" which by default are targeted the 
Perl builtin regex engine, but can be optionally also/only targeted 
alternative engines - even ones unavailable as perl implementations.

Ideally - to me - RP::* modules can tag which engine(s) their paterns 
are supposed to work with, and e.g. Test::RP can then make use of those 
tags for validating the claims, and RP::re can by default serve 
(preferrably pre-compiled, as per the documented recommendation, or) 
compiled with builtin engine, or optionally (re)compile when requested 
to target another engine, or serve uncompiled for engines which it has 
no compiler for.

I am exploring license patterns, where my primary consumer is 
App::Licensecheck but I would want to also be able to serve those 
patterns for competing license validation tools in Debian, some of which 
are written in Python - where I would want to examine how they differ, 
and have my library translate to those other formats as needed.

Maybe that work on autp-translating between regex formats can later be 
isolated as a more general helper library (or maybe such helper library 
already exist and I just missed it so far).

In short: Yes, I think it is useful.  And the lighter on non-core 
modules, the more likely it will find more uses - or so I hope :-)

Concretely, I failed at implementing in RP::License the RE2 and PCRE2 
support I showed a draft of - not due to the concern you raised (if I 
understand you concern correctly then my tests proved that concern to be 
unfounded), but because it turned out that my intended logic to autoload 
(not in the draft I shared) didn't work out, and I gave up for now: 
Currently released code hard-depends on re::engine::RE2 (which is 
urgently needed for App::Licensecheck for the newly added 10-100-fold 
added pattern combination to not slow down scanning10-30 times) and drop 
PCRE2 support (which I have only little experience with and seems less 
suitable for my concrete needs).


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
Yes, I think specifying the regex pattern as source string is a simple way to achieve this. In general specifying the regex pattern as compiled pattern (qr/.../) is preferred due to compile-time checking, but in the case of wanting to choose a regex engine, specifying as string is more appropriate for delayed run-time compilation.

So for simplicity Regexp::Pattern does not need to do anything, the user code can simply compile the regex pattern itself using whatever regex engine it wants.
