### ISSUE TITLE
please support left-only and right-only anchoring

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-Regexp-Pattern#4]
Please extend the `-anchor` option to only prepend `\A` (omit trailing `\z`) when doing `-anchor => 'left'` and vice versa when called as `-anchor => 'right'`.

**Comment by perlancar** [comment]
Could you provide one or two real-world examples?

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-03-12 02:31:29)
> Could you provide one or two real-world examples?

One approach to detecting licenses (which may spot some unknown 
licenses) is to break it into parts and scan stewp-wise:

  This file is licensed under the GNU GPL version 3 or later.
  <--     licensed_under   --><-- gpl --><--   version   -->

That needs "licensed_under" right-anchored and "version" left-anchored.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by perlancar** [comment]
Implemented in 0.2.14.

**Comment by jonassmedegaard** [comment]
Quoting perlancar (2020-04-01 02:56:21)
> Implemented in 0.2.14.

Great. Thanks!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
